name:                attoparsec-fakedata
version:             0.1.0.0
github:              "psibi/attoparsec-fakedata"
license:             BSD3
author:              "Sibi Prabakaran"
maintainer:          "sibi@psibi.in"
copyright:           "Sibi Prabakaran"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/psibi/attoparsec-fakedata#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- text

library:
  source-dirs: src

executables:
  attoparsec-fakedata-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - attoparsec-fakedata

tests:
  attoparsec-fakedata-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - attoparsec-fakedata
    - hspec
