name: Tests

on:
    pull_request:
    push:
      branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    env:
      STACK_ROOT: ${{ github.workspace }}/.stack
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        resolver: [nightly, lts-16, lts-15, lts-14, lts-12]
        # Bugs in GHC make it crash too often to be worth running
        exclude:
          - os: windows-latest
            resolver: nightly
          - os: windows-latest
            resolver: lts-16
          - os: windows-latest
            resolver: lts-15

    steps:
      - name: Clone project
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            ${{ github.workspace }}/.stack
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-

      - name: Build and run tests
        shell: bash
        run: |
            set -ex
            if [ "$RUNNER_OS" == "Linux" ] || [ "$RUNNER_OS" == "macOS" ]; then
                curl -sSL https://get.haskellstack.org/ | sh -s - -f
            fi
            stack test --fast --no-terminal --resolver=${{ matrix.resolver }}
